#!/usr/bin/env ruby

require 'fileutils'

ssh_dir = File.expand_path "~/.ssh"
env_dir = ARGV[0]
env_vars = Dir.entries(env_dir).reject{ |filename| ['.','..'].include?(filename) }
ssh_keys = env_vars.filter{ |var| var.start_with?('GITHUB_DEPLOY_KEY') }

puts "Setting up SSH keys"

ssh_keys.each do |name|
  FileUtils.cp("#{env_dir}/#{name}", "#{ssh_dir}/#{name}")
  FileUtils.chmod 0600, "#{ssh_dir}/#{name}"
end
