#!/bin/bash
# Source: https://www.webfactory.de/blog/using-multiple-ssh-deploy-keys-with-github

# We need ssh-agent to be running
# if we can't find an agent, start one, and restart the script.
if [ -z "$SSH_AUTH_SOCK" ] ; then
  exec ssh-agent bash -c "ssh-add ~/.ssh/GITHUB_DEPLOY_KEY* ; $@"
  exit
fi

# The last argument is the command to be executed on the remote end, which is something
# like "git-upload-pack 'repo_user/repo_name.git'". We need the repo path only, so we
# loop over this last argument to get the last part of if.
for last in ${!#}; do :; done

# Don't use "exec" to run "ssh" below; then the trap won't work.
key_file=$(mktemp -u)
trap "rm -f $key_file" EXIT

eval last=$last

# Try to pick the right key
if [[ $(ssh-add -L | grep $last | wc -l) -ne 0 ]]; then
  ssh-add -L | grep $last > $key_file
  chmod 600 $key_file

  ssh -i $key_file "$@"
else
  ssh "$@"
fi
